# Generated by Django 6.0.5 on 2026-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('atcoder', 'AtCoder')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('url', models.URLField()),
                ('contest_type', models.CharField(blank=True, max_length=50, null=True)),
                ('notify', models.BooleanField(default=True)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_contest_platform_external')],
            },
        ),
    ]
