# Generated by Django 6.0.6 on 2026-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('url', models.URLField()),
                ('notify', models.BooleanField(default=True)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'contest_id'), name='unique_contest_platform')],
            },
        ),
    ]
