# Generated by Django 6.0.6 on 2026-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef')], max_length=255),
        ),
    ]
