# Generated by Django 6.0.6 on 2026-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contest',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef')], max_length=50),
        ),
    ]
